## 100 numpy exercises

### Level 2:

In [53]:
import numpy as np

#### 35. How to get all the dates corresponding to the month of July 2016?

In [3]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 36. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [4]:
A = np.ones(3)*1
A

array([1., 1., 1.])

In [5]:
B = np.ones(3)*2
B

array([2., 2., 2.])

In [6]:
# out=B means store in B
np.add(A,B,out=B)

array([3., 3., 3.])

In [7]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [8]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [9]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 37. Extract the integer part of a random array of positive numbers using 4 different methods

In [10]:
Z = np.random.uniform(0,10,10)

print(Z)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[1.249883   0.07331162 6.22060431 6.94253296 7.05661631 8.05746218
 3.20676262 3.71017126 4.40919288 5.00513074]
[1. 0. 6. 6. 7. 8. 3. 3. 4. 5.]
[1. 0. 6. 6. 7. 8. 3. 3. 4. 5.]
[1. 0. 6. 6. 7. 8. 3. 3. 4. 5.]
[1 0 6 6 7 8 3 3 4 5]
[1. 0. 6. 6. 7. 8. 3. 3. 4. 5.]


#### 38. Create a 5x5 matrix with row values ranging from 0 to 4

In [11]:
Z = np.zeros((5,5))
Z += np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [12]:
# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
Z

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [13]:
# endpoint = 0 means skip 1, and [1:]means skip 0.00
Z = np.linspace(0,1,11,endpoint=False)[1:]
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it

In [14]:
Z = np.random.random(10)
Z

array([0.52827826, 0.14915329, 0.75780919, 0.79959986, 0.76647706,
       0.47555124, 0.84500273, 0.41293608, 0.06617036, 0.5717245 ])

In [15]:
Z.sort()
Z

array([0.06617036, 0.14915329, 0.41293608, 0.47555124, 0.52827826,
       0.5717245 , 0.75780919, 0.76647706, 0.79959986, 0.84500273])

#### 41. How to sum a small array faster than np.sum?

In [16]:
Z = np.arange(10)
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.add.reduce(Z)

np.int64(45)

> np.add.reduce(Z) is faster than np.sum(Z) because it directly uses the ufunc reduction without the extra Python-level overhead and option handling that np.sum carries.

#### 42. Consider two random arrays A and B, check if they are equal

In [18]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)

[1 1 1 1 0]
[1 1 1 0 1]


In [21]:
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


In [22]:
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only)

In [25]:
Z = np.zeros(10)
Z.flags.writeable = False
# Z[0] = 1 : this will give error now

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [26]:
Z = np.random.random((10,2))
Z

array([[0.19907556, 0.01923647],
       [0.71236401, 0.16939847],
       [0.97652145, 0.12730806],
       [0.52820457, 0.2013094 ],
       [0.74239733, 0.70427106],
       [0.94012351, 0.25592411],
       [0.34769587, 0.1953621 ],
       [0.79918174, 0.63332017],
       [0.60502255, 0.95050785],
       [0.23915156, 0.64213214]])

In [27]:
X,Y = Z[:,0], Z[:,1]
print(X)
print(Y)

[0.19907556 0.71236401 0.97652145 0.52820457 0.74239733 0.94012351
 0.34769587 0.79918174 0.60502255 0.23915156]
[0.01923647 0.16939847 0.12730806 0.2013094  0.70427106 0.25592411
 0.1953621  0.63332017 0.95050785 0.64213214]


In [29]:
# R = Radius (Distance from Origin)
R = np.sqrt(X**2+Y**2)
# T = Angle (Direction / Polar Angle)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.20000281 0.73222833 0.984785   0.5652659  1.02330422 0.97433534
 0.39882172 1.01969892 1.12672866 0.68522051]
[0.09632991 0.23346151 0.12963778 0.36412545 0.75904973 0.26578349
 0.5119156  0.6701269  1.00395186 1.21427758]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [34]:
Z = np.random.random(10)
Z

array([0.87080516, 0.75969186, 0.27738819, 0.07957447, 0.97403081,
       0.50104257, 0.090737  , 0.14996299, 0.0472751 , 0.0447301 ])

In [36]:
Z[Z.argmax()] = 0
print(Z)

[0.87080516 0.75969186 0.27738819 0.07957447 0.         0.50104257
 0.090737   0.14996299 0.0472751  0.0447301 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [37]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z

array([[(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [39]:
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [40]:
X = np.arange(8)
Y = X + 0.5
print(X)
print(Y)

[0 1 2 3 4 5 6 7]
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]


In [44]:
# reciprocal / cauchy matrix
C = 1.0 / np.subtract.outer(X, Y)
C

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       ],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667],
       [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
         0.66666667,  2.        , -2.        ]])

In [45]:
# determinant
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable values for each numpy scalar type

In [46]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [47]:
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array

In [50]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

- `np.set_printoptions(threshold=float("inf"))` — Show full arrays without truncation
- Telling numpy to show full array without truncating it

#### 50. How to find the closest value (to a given scalar) in a vector?

In [51]:
Z = np.arange(100)
v = np.random.uniform(0,100)
v

6.351264147249336

In [52]:
index = (np.abs(Z-v)).argmin()
print(Z[index])

6


- Compute distance of every element from v: np.abs(Z - v)
- Find smallest distance index: .argmin()
- Use index to get closest element from Z