## 100 numpy exercises

### Level 2:

In [1]:
import numpy as np

#### 35. How to get all the dates corresponding to the month of July 2016?

In [2]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 36. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [3]:
A = np.ones(3)*1
A

array([1., 1., 1.])

In [4]:
B = np.ones(3)*2
B

array([2., 2., 2.])

In [5]:
# out=B means store in B
np.add(A,B,out=B)

array([3., 3., 3.])

In [6]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [7]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [8]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 37. Extract the integer part of a random array of positive numbers using 4 different methods

In [9]:
Z = np.random.uniform(0,10,10)

print(Z)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[1.62233639 3.60783969 1.06550795 8.60743581 9.57390601 4.03647463
 1.32627093 2.91342818 7.6912141  5.14468998]
[1. 3. 1. 8. 9. 4. 1. 2. 7. 5.]
[1. 3. 1. 8. 9. 4. 1. 2. 7. 5.]
[1. 3. 1. 8. 9. 4. 1. 2. 7. 5.]
[1 3 1 8 9 4 1 2 7 5]
[1. 3. 1. 8. 9. 4. 1. 2. 7. 5.]


#### 38. Create a 5x5 matrix with row values ranging from 0 to 4

In [10]:
Z = np.zeros((5,5))
Z += np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [11]:
# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
Z

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [12]:
# endpoint = 0 means skip 1, and [1:]means skip 0.00
Z = np.linspace(0,1,11,endpoint=False)[1:]
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it

In [13]:
Z = np.random.random(10)
Z

array([0.84093657, 0.26344478, 0.9079629 , 0.2418206 , 0.61198406,
       0.41154046, 0.11893627, 0.37702187, 0.25306149, 0.65878042])

In [14]:
Z.sort()
Z

array([0.11893627, 0.2418206 , 0.25306149, 0.26344478, 0.37702187,
       0.41154046, 0.61198406, 0.65878042, 0.84093657, 0.9079629 ])

#### 41. How to sum a small array faster than np.sum?

In [15]:
Z = np.arange(10)
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.add.reduce(Z)

np.int64(45)

> np.add.reduce(Z) is faster than np.sum(Z) because it directly uses the ufunc reduction without the extra Python-level overhead and option handling that np.sum carries.

#### 42. Consider two random arrays A and B, check if they are equal

In [17]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)

[1 1 0 0 1]
[0 0 1 1 0]


In [18]:
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


In [19]:
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only)

In [20]:
Z = np.zeros(10)
Z.flags.writeable = False
# Z[0] = 1 : this will give error now

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [21]:
Z = np.random.random((10,2))
Z

array([[0.68923863, 0.13411302],
       [0.87902338, 0.30641953],
       [0.12762355, 0.88293817],
       [0.76292091, 0.65329231],
       [0.22752938, 0.9645189 ],
       [0.95100574, 0.87937118],
       [0.57364711, 0.46913906],
       [0.45023531, 0.59915829],
       [0.82240842, 0.13764317],
       [0.14453363, 0.7373992 ]])

In [22]:
X,Y = Z[:,0], Z[:,1]
print(X)
print(Y)

[0.68923863 0.87902338 0.12762355 0.76292091 0.22752938 0.95100574
 0.57364711 0.45023531 0.82240842 0.14453363]
[0.13411302 0.30641953 0.88293817 0.65329231 0.9645189  0.87937118
 0.46913906 0.59915829 0.13764317 0.7373992 ]


In [23]:
# R = Radius (Distance from Origin)
R = np.sqrt(X**2+Y**2)
# T = Angle (Direction / Polar Angle)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.70216536 0.93090012 0.8921141  1.00440986 0.9909926  1.29526275
 0.74105497 0.74946814 0.83384726 0.75143033]
[0.19217999 0.33541893 1.42724639 0.70814256 1.33913226 0.74628162
 0.68551167 0.9263702  0.16582899 1.37724544]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [24]:
Z = np.random.random(10)
Z

array([0.60130466, 0.41442186, 0.38356942, 0.76568578, 0.45515769,
       0.80937859, 0.50962737, 0.0712559 , 0.74343034, 0.3266125 ])

In [25]:
Z[Z.argmax()] = 0
print(Z)

[0.60130466 0.41442186 0.38356942 0.76568578 0.45515769 0.
 0.50962737 0.0712559  0.74343034 0.3266125 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [26]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z

array([[(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [27]:
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [28]:
X = np.arange(8)
Y = X + 0.5
print(X)
print(Y)

[0 1 2 3 4 5 6 7]
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]


In [29]:
# reciprocal / cauchy matrix
C = 1.0 / np.subtract.outer(X, Y)
C

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       ],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667],
       [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
         0.66666667,  2.        , -2.        ]])

In [30]:
# determinant
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable values for each numpy scalar type

In [31]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [32]:
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array

In [33]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

- `np.set_printoptions(threshold=float("inf"))` — Show full arrays without truncation
- Telling numpy to show full array without truncating it

#### 50. How to find the closest value (to a given scalar) in a vector?

In [34]:
Z = np.arange(100)
v = np.random.uniform(0,100)
v

17.32318837655642

In [35]:
index = (np.abs(Z-v)).argmin()
print(Z[index])

17


- Compute distance of every element from v: np.abs(Z - v)
- Find smallest distance index: .argmin()
- Use index to get closest element from Z

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [37]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
Z

array([(([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.]))],
      dtype=[('position', [('x', '<f8', (1,)), ('y', '<f8', (1,))]), ('color', [('r', '<f8', (1,)), ('g', '<f8', (1,)), ('b', '<f8', (1,))])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [38]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
print(Z)
print(X)
print(Y)

[[0.12304798 0.23171272]
 [0.71046073 0.61021959]
 [0.67809582 0.29100713]
 [0.56189311 0.91855382]
 [0.80142364 0.02136879]
 [0.94253609 0.27672589]
 [0.19274968 0.18133294]
 [0.75866356 0.75429287]
 [0.42818084 0.92815789]
 [0.69259698 0.25616679]]
[[0.12304798 0.71046073 0.67809582 0.56189311 0.80142364 0.94253609
  0.19274968 0.75866356 0.42818084 0.69259698]]
[[0.23171272 0.61021959 0.29100713 0.91855382 0.02136879 0.27672589
  0.18133294 0.75429287 0.92815789 0.25616679]]


In [39]:
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.69879982 0.558206   0.81506795 0.71023806 0.82072343
  0.08600261 0.82285915 0.76035646 0.57007374]
 [0.69879982 0.         0.320849   0.34226063 0.59583514 0.40629671
  0.67228602 0.15192308 0.42516667 0.35450316]
 [0.558206   0.320849   0.         0.63821464 0.29650394 0.26482562
  0.49758347 0.47023912 0.68441112 0.03773768]
 [0.81506795 0.34226063 0.63821464 0.         0.92860964 0.74621188
  0.82447651 0.25632064 0.13405674 0.6751593 ]
 [0.71023806 0.59583514 0.29650394 0.92860964 0.         0.29175328
  0.62934293 0.73417037 0.98060015 0.25879209]
 [0.82072343 0.40629671 0.26482562 0.74621188 0.29175328 0.
  0.75583032 0.51174146 0.83001504 0.25078324]
 [0.08600261 0.67228602 0.49758347 0.82447651 0.62934293 0.75583032
  0.         0.80532081 0.78305513 0.50541808]
 [0.82285915 0.15192308 0.47023912 0.25632064 0.73417037 0.51174146
  0.80532081 0.         0.3734272  0.50248819]
 [0.76035646 0.42516667 0.68441112 0.13405674 0.98060015 0.83001504
  0.78305513 0.37342

In [40]:
# Much faster with scipy
import scipy
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.45792158 0.18040809 0.88049791 0.62391154 0.7586873
  0.14987741 0.8730122  0.24317658 0.58879721]
 [0.45792158 0.         0.63830364 0.70959416 0.83841909 0.64211992
  0.59908355 0.76341558 0.68994224 0.76576169]
 [0.18040809 0.63830364 0.         1.00128563 0.62071902 0.87160782
  0.07417932 0.97645097 0.10351573 0.60963956]
 [0.88049791 0.70959416 1.00128563 0.         0.64593857 0.1356937
  0.92841539 0.1155636  0.97276643 0.57088672]
 [0.62391154 0.83841909 0.62071902 0.64593857 0.         0.52147826
  0.55650821 0.55862628 0.53628168 0.0847319 ]
 [0.7586873  0.64211992 0.87160782 0.1356937  0.52147826 0.
  0.79820246 0.12382616 0.83954301 0.44311799]
 [0.14987741 0.59908355 0.07417932 0.92841539 0.55650821 0.79820246
  0.         0.90245112 0.09336613 0.54075935]
 [0.8730122  0.76341558 0.97645097 0.1155636  0.55862628 0.12382616
  0.90245112 0.         0.93672078 0.48981927]
 [0.24317658 0.68994224 0.10351573 0.97276643 0.53628168 0.83954301
  0.09336613 0.9367207

##### NumPy
- Manually computes pairwise distances using array broadcasting.
##### SciPy
- Uses optimised cdist for efficient distance computation.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [41]:
Z = (np.random.rand(10)*100).astype(np.float32)
Z

array([88.29502   , 25.072973  , 43.691467  , 11.946962  , 51.3661    ,
       54.682014  , 19.060247  ,  0.54985213,  0.27489668,  6.0288177 ],
      dtype=float32)

In [42]:
Y = Z.view(np.int32)
Y

array([1118869261, 1103664499, 1110361104, 1094657730, 1112372963,
       1113242210, 1100512099, 1057800988, 1049411394, 1086385171],
      dtype=int32)

In [43]:
Y[:] = Z
print(Y)

[88 25 43 11 51 54 19  0  0  6]


- `Z` is a float32 array (10 random values).
- `Y = Z.view(np.int32)` makes a bitwise re-interpretation of the same memory.
- `Y[:] = Z` assigns float values into an int32 array → float → int conversion happens.
- Final result: `Y` contains the integer-truncated values of `Z`.

#### 54. How to read the following file?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [45]:
from io import StringIO
# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype = int, filling_values = 0)
print(Z)

[[ 1  2  3  4  5]
 [ 6  0  0  7  8]
 [ 0  0  9 10 11]]


- `StringIO` creates an in-memory mock file.
- `np.genfromtxt` reads messy CSV-like data safely.
- Missing values are replaced with `0` using `filling_values`.
- Output is a clean integer matrix with gaps filled.

#### 55. What is the equivalent of enumerate for numpy arrays?

In [46]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 57. How to randomly place p elements in a 2D array?

In [47]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix

In [48]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.57261337  0.31469507 -0.01068575 -0.16951505 -0.33200084  0.20955684
   0.17039496  0.08772288  0.1264918   0.17595346]
 [ 0.03044307 -0.32541291  0.03761364 -0.21565466  0.11934523 -0.28602976
   0.02260239 -0.22091325  0.44667006  0.3913362 ]
 [ 0.03534708  0.17622528  0.43844459 -0.20476972  0.38996746 -0.30678177
   0.02023836  0.29421061 -0.50293749 -0.33994439]
 [ 0.31047335 -0.11294397  0.28520905  0.21566891  0.04103877  0.24933385
  -0.16038911 -0.16939562 -0.23688088 -0.42211436]
 [ 0.03890176 -0.07585077  0.61621258 -0.37004665  0.32740229 -0.24000906
   0.07062397 -0.34129654  0.05378441 -0.07972198]]


#### 59. How to sort an array by the nth column?

In [49]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[0 5 8]
 [2 8 2]
 [9 7 9]]
[[0 5 8]
 [9 7 9]
 [2 8 2]]


#### 60. How to tell if a given 2D array has null columns?

In [50]:
# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

False
[False False  True]


For Z with 0 as null
- `Z.any(axis=0)` → checks if column has any non-zero
- `~` inverts it → identifies all-zero columns
- `.any()` → checks if any such column exists

For Z with NaN as null
- `np.isnan(Z)` → detect NaN entries
- `.all(axis=0)` → True where every element in the column is NaN

#### 61. Find the nearest value from a given value in an array

In [51]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4735449962030436


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [52]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


- `A` is shape (3,1)
- `B` is shape (1,3)
- They broadcast to (3,3)
- `nditer([A,B,None])` creates an iterator with an auto-generated output array
- Inside the loop: `z[...] = x + y` writes results element-wise
- The final output is the broadcasted sum matrix

#### 63. Create an array class that has a name attribute

In [53]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [55]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


In [56]:
# Faster version
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64


Method 1 (simple NumPy)
- Converts image RGB to `(n,3)`
- Uses `np.unique(..., axis=0)`
- Easy to understand
- Slower

Method 2 (optimized)
- Encodes each RGB pixel into a 24-bit integer
- Uses `np.unique()` on integers
- Much faster due to scalar comparisons
- Ideal for large images