## 100 numpy exercises

### Level 2:

In [1]:
import numpy as np

#### 35. How to get all the dates corresponding to the month of July 2016?

In [2]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 36. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [3]:
A = np.ones(3)*1
A

array([1., 1., 1.])

In [4]:
B = np.ones(3)*2
B

array([2., 2., 2.])

In [5]:
# out=B means store in B
np.add(A,B,out=B)

array([3., 3., 3.])

In [6]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [7]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [8]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 37. Extract the integer part of a random array of positive numbers using 4 different methods

In [9]:
Z = np.random.uniform(0,10,10)

print(Z)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[9.62211785 9.31183831 8.02980011 3.15791511 5.43388623 2.95700549
 9.28036156 4.51360683 9.47832527 1.0921342 ]
[9. 9. 8. 3. 5. 2. 9. 4. 9. 1.]
[9. 9. 8. 3. 5. 2. 9. 4. 9. 1.]
[9. 9. 8. 3. 5. 2. 9. 4. 9. 1.]
[9 9 8 3 5 2 9 4 9 1]
[9. 9. 8. 3. 5. 2. 9. 4. 9. 1.]


#### 38. Create a 5x5 matrix with row values ranging from 0 to 4

In [10]:
Z = np.zeros((5,5))
Z += np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [11]:
# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
Z

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [12]:
# endpoint = 0 means skip 1, and [1:]means skip 0.00
Z = np.linspace(0,1,11,endpoint=False)[1:]
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it

In [13]:
Z = np.random.random(10)
Z

array([0.93682271, 0.29514684, 0.83715873, 0.47339356, 0.82177592,
       0.0148998 , 0.67714744, 0.09885743, 0.70470968, 0.95966917])

In [14]:
Z.sort()
Z

array([0.0148998 , 0.09885743, 0.29514684, 0.47339356, 0.67714744,
       0.70470968, 0.82177592, 0.83715873, 0.93682271, 0.95966917])

#### 41. How to sum a small array faster than np.sum?

In [15]:
Z = np.arange(10)
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.add.reduce(Z)

np.int64(45)

> np.add.reduce(Z) is faster than np.sum(Z) because it directly uses the ufunc reduction without the extra Python-level overhead and option handling that np.sum carries.

#### 42. Consider two random arrays A and B, check if they are equal

In [17]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)

[0 0 1 1 1]
[0 0 1 1 0]


In [18]:
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


In [19]:
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only)

In [20]:
Z = np.zeros(10)
Z.flags.writeable = False
# Z[0] = 1 : this will give error now

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [21]:
Z = np.random.random((10,2))
Z

array([[0.6812548 , 0.80339119],
       [0.44173263, 0.95337852],
       [0.19046585, 0.72314193],
       [0.31487582, 0.54247923],
       [0.83744259, 0.36530261],
       [0.75969883, 0.82661596],
       [0.69235952, 0.55225887],
       [0.23951705, 0.8093949 ],
       [0.28754823, 0.27990359],
       [0.58105329, 0.68071269]])

In [22]:
X,Y = Z[:,0], Z[:,1]
print(X)
print(Y)

[0.6812548  0.44173263 0.19046585 0.31487582 0.83744259 0.75969883
 0.69235952 0.23951705 0.28754823 0.58105329]
[0.80339119 0.95337852 0.72314193 0.54247923 0.36530261 0.82661596
 0.55225887 0.8093949  0.27990359 0.68071269]


In [23]:
# R = Radius (Distance from Origin)
R = np.sqrt(X**2+Y**2)
# T = Angle (Direction / Polar Angle)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.05334966 1.0507418  0.74780444 0.62724038 0.91364987 1.12269153
 0.88563625 0.84409035 0.40128544 0.89498195]
[0.86747967 1.13690938 1.31325879 1.04488449 0.41132895 0.82755719
 0.67330488 1.28308581 0.77192711 0.86421859]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [24]:
Z = np.random.random(10)
Z

array([0.10529866, 0.93875821, 0.06487083, 0.38829012, 0.7547521 ,
       0.7667786 , 0.09922216, 0.4664172 , 0.25748199, 0.71924462])

In [25]:
Z[Z.argmax()] = 0
print(Z)

[0.10529866 0.         0.06487083 0.38829012 0.7547521  0.7667786
 0.09922216 0.4664172  0.25748199 0.71924462]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [26]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z

array([[(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [27]:
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [28]:
X = np.arange(8)
Y = X + 0.5
print(X)
print(Y)

[0 1 2 3 4 5 6 7]
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]


In [29]:
# reciprocal / cauchy matrix
C = 1.0 / np.subtract.outer(X, Y)
C

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       ],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667],
       [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
         0.66666667,  2.        , -2.        ]])

In [30]:
# determinant
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable values for each numpy scalar type

In [31]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [32]:
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array

In [33]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

- `np.set_printoptions(threshold=float("inf"))` — Show full arrays without truncation
- Telling numpy to show full array without truncating it

#### 50. How to find the closest value (to a given scalar) in a vector?

In [34]:
Z = np.arange(100)
v = np.random.uniform(0,100)
v

46.767046282605804

In [35]:
index = (np.abs(Z-v)).argmin()
print(Z[index])

47


- Compute distance of every element from v: np.abs(Z - v)
- Find smallest distance index: .argmin()
- Use index to get closest element from Z