## 100 numpy exercises

### Level 1:

#### 1. Import the numpy package under the name `np`

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [2]:
np.__version__

'2.1.3'

In [3]:
np.__config__

<module 'numpy.__config__' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\numpy\\__config__.py'>

#### 3. Create a null vector of size 10

In [4]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array

In [5]:
print("%d bytes" % (z.size * z.itemsize))

80 bytes


In [6]:
# Simpler alternative
print("%d bytes" % z.nbytes)

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line?

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [8]:
null_vector = np.zeros(10)
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49

In [9]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last)

In [10]:
vector = np.arange(1, 11)
vector[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [12]:
arr1 = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(arr1)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [14]:
np.random.random((3,3,3))

array([[[0.03533294, 0.07309847, 0.87219806],
        [0.66007303, 0.19406822, 0.33242116],
        [0.52875033, 0.09039396, 0.29048323]],

       [[0.60980332, 0.76845108, 0.85405387],
        [0.6424501 , 0.93991866, 0.82341896],
        [0.61329693, 0.20328137, 0.77152323]],

       [[0.85719306, 0.13975978, 0.79368836],
        [0.83404494, 0.96465635, 0.61138338],
        [0.65850132, 0.19737574, 0.86872386]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [15]:
arr2 = np.random.random((10, 10))
arr2

array([[0.73325893, 0.43672596, 0.32921032, 0.67238858, 0.68877153,
        0.57577461, 0.48608175, 0.68344141, 0.31305206, 0.13221225],
       [0.68529635, 0.80043081, 0.41449117, 0.41650234, 0.62803506,
        0.08351171, 0.05085063, 0.5363339 , 0.01674208, 0.37073566],
       [0.5644112 , 0.83776902, 0.54118545, 0.94971112, 0.37250966,
        0.99207145, 0.13496044, 0.53582635, 0.85316741, 0.06429788],
       [0.21107157, 0.47061543, 0.43908011, 0.53652383, 0.76768955,
        0.52201845, 0.04566508, 0.91011914, 0.72839744, 0.70401137],
       [0.83938516, 0.48569371, 0.00154255, 0.57936761, 0.74088423,
        0.84623994, 0.45609527, 0.49587477, 0.90929944, 0.26820826],
       [0.22542994, 0.74124965, 0.41605098, 0.8651365 , 0.54192776,
        0.04079511, 0.93644978, 0.46381484, 0.20709045, 0.74159228],
       [0.49133259, 0.11398944, 0.17693745, 0.09560802, 0.38705006,
        0.85227077, 0.48358196, 0.09213196, 0.98367537, 0.77657639],
       [0.58773923, 0.80462679, 0.1553575

In [16]:
print(arr2.max())

0.9920714516508585


In [17]:
print(arr2.min())

0.0015425471756529419


#### 14. Create a random vector of size 30 and find the mean value

In [18]:
arr3 = np.random.random(30)
arr3

array([0.58188148, 0.64450639, 0.99961809, 0.51524859, 0.76844789,
       0.69246519, 0.53499177, 0.87300682, 0.16696931, 0.50806917,
       0.85373744, 0.90953191, 0.17676214, 0.83540224, 0.65100851,
       0.23105746, 0.38195296, 0.68874096, 0.15563333, 0.43729439,
       0.15836642, 0.39897712, 0.87557426, 0.28943782, 0.8174506 ,
       0.71393431, 0.72289368, 0.56604051, 0.58817023, 0.97327863])

In [19]:
print(arr3.mean())

0.5903483197893519


#### 15. Create a 2d array with 1 on the border and 0 inside

In [20]:
arr4 = np.ones((10, 10))
arr4[1:-1,1:-1] = 0
arr4

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [21]:
arr5 = np.ones((5, 5))
arr5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
arr5 = np.pad(arr5, pad_width=1, mode='constant', constant_values=0)
arr5

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### `pad_width=1`

This means:

- Add 1 layer of padding on every side
- Applies to all dimensions
- For a 2D array:
  - 1 row on top
  - 1 row on bottom
  - 1 column on left
  - 1 column on right

So the padded array becomes larger by +2 in each dimension.

Example:
If `arr5` is shape `(m, n)`, new shape = `(m+2, n+2)`.

#### `mode='constant'`
This means the padding values will be constant (not reflected, repeated, etc.).

#### `constant_values=0`

This sets the padding value to 0.
So the border is filled with zeros.

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [23]:
# Any arithmetic operation involving NaN produces NaN
print(0 * np.nan)

nan


In [24]:
# NaN is not equal to anything, including itself.
print(np.nan == np.nan)

False


In [25]:
# Any comparison involving NaN returns False, except !=, which returns True.
# np.nan is unordered: it is not greater, less, or equal to anything.
print(np.inf > np.nan)

False


In [26]:
# Any arithmetic with NaN → NaN.
print(np.nan - np.nan)

nan


In [27]:
print(np.nan in set([np.nan]))

True


Output: `True`, surprisingly!

Why:
This seems contradictory because `np.nan` != `np.nan`, but:

#### Sets use hashing for membership
- `np.nan` has a stable hash value.
- The hash is used first to find the bucket in the set.
- Equality is checked only afterward—but since it's the same object, it is treated as found.

So `x in set([x])` is always true, even if `x != x`.

> Using NaN as a set key works, but using multiple NaNs can behave oddly.

In [28]:
print(0.3 == 3 * 0.1)

False


Output: `False`

Why:
This is due to binary floating-point precision.

- `0.1` cannot be represented exactly in binary.
- `3 * 0.1` becomes `0.30000000000000004`

This is not exactly equal to 0.3

In [29]:
print(3 * 0.1)

0.30000000000000004


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [30]:
arr6 = np.diag(1+np.arange(4),k=-1)
arr6

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [31]:
# explanation
np.arange(4)

array([0, 1, 2, 3])

In [32]:
1 + np.arange(4)

array([1, 2, 3, 4])

`np.diag(values, k=-1)`

`np.diag(v, k)` places the 1D array `v` on a diagonal:

- `k = 0` → main diagonal
- `k = 1` → 1 above main
- `k = -1` → 1 below main (sub-diagonal)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [33]:
arr7 = np.zeros((8,8),dtype=int)
# odd columns
arr7[1::2,::2] = 1
# even columns
arr7[::2,1::2] = 1
arr7

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [34]:
# Index 99 is a location in the flattened (1D) version of this array.
# np.unravel_index(99, (6,7,8)) finds the corresponding (i, j, k) position in the 3-D array using row-major (C-style) order.
np.unravel_index(99,(6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function
`np.tile(A, (m, n))` repeats array `A`:
- `m` times vertically (down)
- `n` times horizontally (right)

In [35]:
np.tile( np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix

In [36]:
arr8 = np.random.random((5,5))
arr8

array([[0.75569246, 0.23907419, 0.01473796, 0.84289145, 0.051206  ],
       [0.99439918, 0.86874238, 0.78176994, 0.86631548, 0.53307378],
       [0.62520252, 0.70883959, 0.5364132 , 0.68080478, 0.74101263],
       [0.89898553, 0.4456117 , 0.84796628, 0.20298934, 0.12418634],
       [0.39717435, 0.38154086, 0.90422752, 0.43342916, 0.27523666]])

In [37]:
arr8 = (arr8 - np.mean (arr8)) / (np.std (arr8))
arr8

array([[ 0.65728143, -1.13336799, -1.91093931,  0.95952164, -1.78453753],
       [ 1.48466223,  1.0491235 ,  0.7476685 ,  1.04071163, -0.11433668],
       [ 0.20499052,  0.49488477, -0.10276194,  0.39771338,  0.60639969],
       [ 1.15394921, -0.41748882,  0.97711149, -1.25844161, -1.53158052],
       [-0.58537741, -0.63956459,  1.17211845, -0.45971467, -1.00802536]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [38]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [39]:
mat_mul = np.matmul(np.ones((5, 3)), np.ones((3, 2)))
mat_mul

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [40]:
# Alternative solution, in Python 3.5 and above
mat_mul2 = np.ones((5,3)) @ np.ones((3,2))
mat_mul2

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [41]:
arr9 = np.arange(11)
arr9[(3 < arr9) & (arr9 < 8)] *= -1
arr9

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script?
```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [42]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


- Python's sum = `sum(iterable, start_value)`
- NumPy's sum = `numpy.sum(array, axis)`

#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

- **`Z**Z`** → Legal  
  - Performs element-wise exponentiation

- **`2 << Z >> 2`** → Legal  
  - Applies element-wise bitwise left/right shifts

- **`Z <- Z`** → Illegal  
  - `<-` is not a valid operator in Python

- **`1j * Z`** → Legal  
  - Complex scalar multiplied with array, result becomes complex

- **`Z/1/1`** → Legal  
  - Standard element-wise division

- **`Z < Z > Z`** → Illegal  
  - NumPy arrays cannot be used in chained comparisons

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

- **`np.array(0) / np.array(0)`** → `nan`  
  - Because `0/0` is invalid → results in **NaN** (floating-point undefined division)
- **`np.array(0) // np.array(0)`** → `0`  
  - NumPy gives a warning but returns **0** for floor-division by zero
- **`np.array([np.nan]).astype(int).astype(float)`** → large negative number  
  - `NaN` → converted to **minimum int value** → then converted back to float

#### 29. How to round away from zero a float array ?

In [43]:
arr10 = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(arr10)), arr10))

# More readable but less efficient
print(np.where(arr10>0, np.ceil(arr10), np.floor(arr10)))

[ -7.   5.  -6.  -3.   3.  -2.   6. -10.  -7.  10.]
[ -7.   5.  -6.  -3.   3.  -2.   6. -10.  -7.  10.]


- **`np.copysign(np.ceil(np.abs(arr10)), arr10)`**
  - Uses a math trick: take absolute value → apply `ceil()` → restore original sign
  - Produces the same result as the conditional method
  - Very fast (fully vectorized)

- **`np.where(arr10 > 0, np.ceil(arr10), np.floor(arr10))`**
  - Uses if–else branching: positive → `ceil()`, negative → `floor()`
  - Produces the same result
  - Slower due to conditional checks

---

- **`np.ceil(x)`**
  - Rounds *up* to the next integer
  - Examples:
    - `np.ceil(3.2)` → `4`
    - `np.ceil(-3.2)` → `-3`
- **`np.floor(x)`**
  - Rounds *down* to the previous integer
  - Examples:
    - `np.floor(3.7)` → `3`
    - `np.floor(-3.7)` → `-4`
- **`np.round(x)`**
  - Rounds to the nearest integer (uses banker’s rounding)
  - Examples:
    - `np.round(3.5)` → `4`
    - `np.round(2.5)` → `2`
- **`np.trunc(x)`**
  - Truncates decimal part → rounds *toward zero*
  - Examples:
    - `np.trunc(3.8)` → `3`
    - `np.trunc(-3.8)` → `-3`

#### 30. How to find common values between two arrays?

In [44]:
Z1 = np.random.randint(0,10,10)
Z1

array([5, 8, 1, 8, 8, 9, 9, 9, 5, 6], dtype=int32)

In [45]:
Z2 = np.random.randint(0,10,10)
Z2

array([6, 7, 7, 3, 8, 3, 1, 3, 1, 5], dtype=int32)

In [46]:
np.intersect1d(Z1,Z2)

array([1, 5, 6, 8], dtype=int32)

#### 31. How to ignore all numpy warnings (not recommended)?

In [47]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [48]:
# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

- `np.sqrt(-1)` → `nan` (real-only sqrt)
- `np.emath.sqrt(-1)` → `1j` (complex sqrt)
- `np.sqrt(-1)` == `np.emath.sqrt(-1)` → False

#### 33. How to get the dates of yesterday, today and tomorrow?

In [49]:
yesterday = np.datetime64('today') - np.timedelta64(1)
yesterday

np.datetime64('2025-12-03')

In [50]:
today     = np.datetime64('today')
today

np.datetime64('2025-12-04')

In [51]:
tomorrow  = np.datetime64('today') + np.timedelta64(1)
tomorrow

np.datetime64('2025-12-05')

In [52]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 34. Consider a generator function that generates 10 integers and use it to build an array

In [54]:
def generate():
    for x in range(10):
        yield x
arr11 = np.fromiter(generate(),dtype=float,count=-1)
arr11

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

- `generate()` yields numbers 0–9.
- `np.fromiter()` consumes the generator and creates a NumPy array.
`count=-1` → read all items.
- Output is a float array