### Operations on numpy array

In [2]:
# import numpy
import numpy as np

In [3]:
# create 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Basic slicing
arr[2:7]

array([3, 4, 5, 6, 7])

In [5]:
# with step
arr[1:8:2]

array([2, 4, 6, 8])

In [6]:
# with negative indexing
arr[-1:-7:-2]

array([10,  8,  6])

In [7]:
# create 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# specific element
arr_2d[1, 2]

np.int64(6)

In [9]:
# entire row
arr_2d[1]

array([4, 5, 6])

In [10]:
# entire column
arr_2d[:, 1]

array([2, 5, 8])

In [11]:
# sorting in 1D arrays
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
np.sort(unsorted)

array([1, 1, 2, 3, 4, 5, 6, 9])

In [12]:
# sorting in 2D array
unsorted_2d = np.array([[3, 1], [1, 2], [2, 3]])
unsorted_2d

array([[3, 1],
       [1, 2],
       [2, 3]])

In [13]:
# row wise
np.sort(unsorted_2d, axis=1)

array([[1, 3],
       [1, 2],
       [2, 3]])

In [14]:
# column-wise
np.sort(unsorted_2d, axis=0)

array([[1, 1],
       [2, 2],
       [3, 3]])

In [15]:
# filter
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# even numbers
even = numbers[numbers % 2 == 0]
even

array([ 2,  4,  6,  8, 10])

In [16]:
# filter with mask
mask = numbers >= 5
numbers[mask]

array([ 5,  6,  7,  8,  9, 10])

In [17]:
# using where
where_result = np.where(numbers > 5)
numbers[where_result]

array([ 6,  7,  8,  9, 10])

In [18]:
# using condition structure in where
# condition, if yes then * 2 else print only
condition_array = np.where(numbers > 5, numbers * 2, numbers)
condition_array

array([ 1,  2,  3,  4,  5, 12, 14, 16, 18, 20])

In [19]:
# concatenation of arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
combined = np.concatenate((arr1, arr2))
combined

array([1, 2, 3, 4, 5, 6])

In [20]:
# adding values (row)
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])
np.vstack((original, new_row))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
# adding values (column)
new_col = ([[7], [8]])
np.hstack((original, new_col))

array([[1, 2, 7],
       [3, 4, 8]])

In [22]:
# delete element from 1D
arr = np.array([1, 2, 3, 4, 5])
np.delete(arr, 2)

array([1, 2, 4, 5])

In [23]:
# axis usage
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [24]:
print("Sum along axis 0 (columns):", data.sum(axis=0))
print("Sum along axis 1 (rows):", data.sum(axis=1))

Sum along axis 0 (columns): [4 6]
Sum along axis 1 (rows): [3 7]


In [25]:
# matrix multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
a @ b

array([[19, 22],
       [43, 50]])

In [26]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
a

array([[1, 2],
       [3, 4]])

In [27]:
b

array([[5, 6],
       [7, 8]])

In [28]:
# hstack
print("Horizontal Stack:\n", np.hstack((a, b)))

Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [29]:
# vstack
print("Vertical Stack:\n", np.vstack((a, b)))

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [30]:
# stack
print("Stack (3D):\n", np.stack((a, b)))

Stack (3D):
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
arr = np.arange(16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
# hsplit
print("Horizontal Split:")
np.hsplit(arr, 2)

Horizontal Split:


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [33]:
# vsplit
print("Vertical Split:")
np.vsplit(arr, 2)

Vertical Split:


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]