### Numpy Foundation, creation of array and methods

In [33]:
# import numpy
import numpy as np

In [34]:
# create an array using a list
# 1D
arr_1d = np.array([1, 2, 3, 4, 5])
arr_1d

array([1, 2, 3, 4, 5])

In [35]:
# 2D
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
# Python list vs Numpy array
# multiplication in list
py_list = [1, 2, 3]
py_list * 2

[1, 2, 3, 1, 2, 3]

In [37]:
# multiplication in numpy array
np_array = np.array([1, 2, 3])
np_array * 2

array([2, 4, 6])

In [38]:
# creating arrays from scratch
# zeros
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
# ones
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
# full ( specific element repetition)
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [41]:
# random
np.random.random((2, 3))

array([[0.49289175, 0.56513368, 0.45656478],
       [0.6720787 , 0.70614802, 0.58872208]])

In [42]:
# randint
np.random.randint(1, 10, 5)

array([8, 1, 6, 6, 5], dtype=int32)

In [43]:
# sequence
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [44]:
# linspace: Creates evenly spaced numbers between start and stop.
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
# logspace: Similar to linspace(), but creates values on a logarithmic scale (base 10).
np.logspace(1, 3, 5)

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [46]:
# vector
np.array([1, 2, 3])

array([1, 2, 3])

In [47]:
# matrix
np.array([[1, 2, 3],
          [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
# tensor
np.array([[[1, 2], [3, 4]],
          [[5, 6], [7, 8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [49]:
# Array properties
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
# shape ( rows and columns )
arr.shape

(2, 3)

In [50]:
# dimension
arr.ndim

2

In [51]:
# number of elements
arr.size

6

In [52]:
# data type
arr.dtype

dtype('int64')

In [53]:
# gives total number of rows (for 2D) or elements (for 1D)
print(len(arr))

2


In [54]:
# Array reshaping
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
# change shape ( rows and columns )
reshaped = arr.reshape((3, 4))
reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
# reshape with unknown dimension
# # multiple rows, 1 column
arr.reshape(-1, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [57]:
# 1 row, multiple columns
arr.reshape(1, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [58]:
# flatten the array ( copy of array )
flattened = reshaped.flatten()
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
# ravel return view instead of copy ( Orignal array )
raveled = reshaped.ravel()
raveled

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
# transpose
reshaped.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [61]:
# vector addition
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([6, 7, 8, 9, 10])
vector1 + vector2

array([ 7,  9, 11, 13, 15])

In [62]:
# vector multiplication
vector1 * vector2

array([ 6, 14, 24, 36, 50])

In [63]:
# dot product
np.dot(vector1, vector2)

np.int64(130)

In [64]:
# to find angle
np.arccos(np.dot(vector1, vector2) / (np.linalg.norm(vector1) * np.linalg.norm(vector2)))

np.float64(0.26554161733900966)