## NUMPY COMPLETE GUIDE

### 1. What is NumPy?

#### In deep:

**NumPy** (short form of **Numerical Python**) is an open-source Python library used for 
numerical computing. It provides tools for working efficiently with arrays, matrices, and 
mathematical functions. 

NumPy introduces a new data structure called the **ndarray** (n-dimensional array), 
which is much faster and more memory-efficient than Python’s built-in lists for 
numerical operations.

Important Features:

- **Multidimensional Arrays:** 
Efficient storage and manipulation of large datasets (e.g., 1D, 2D, 3D arrays).

- **Mathematical Functions:**
A wide range of mathematical operations — linear algebra, Fourier transforms, 
random number generation, etc.

- **Vectorization:**
Operations on entire arrays without explicit loops, making code cleaner and faster.

- **Interoperability:**
Works well with other libraries like Pandas, Matplotlib, TensorFlow, PyTorch etc.

#### In brief:

NumPy (Numerical Python) is the fastest numerical computing library in Python.
It provides:

- ndarray → fast multi-dimensional arrays
- vectorized operations → no loops, extremely fast
- mathematical functions
- linear algebra
- random number generation

NumPy is written in C, which is why it's much faster than Python lists.

### 2. Why NumPy Instead of Lists?

- **Speed**
  - Lists → Slow  
  - NumPy → **50–100x faster**

- **Memory**
  - Lists → High  
  - NumPy → **Low memory usage**

- **Operations**
  - Lists → Uses loops  
  - NumPy → **Vectorized operations (no loops)**

- **Data Types**
  - Lists → Mixed data types allowed  
  - NumPy → **Homogeneous data types**

- **Machine Learning Support**
  - Lists → Poor support  
  - NumPy → **Essential for ML & scientific computing**

In [1]:
# Performance Comparison 
import numpy as np  
import time

size = 10_000_000 # large data set of 10 million numbers  

# Python Lists  
python_list = list(range(size))  
start = time.time() 

list_squared = [x**2 for x in python_list] # square of all nums 

end = time.time()  
print("Python list time:", end - start, "seconds")  

# NumPy Arrays  
np_array = np.array(python_list)  
start = time.time()  

array_squared = np_array ** 2 # vectorized operation 

end = time.time() 
print("NumPy array time:", end - start, "seconds")

Python list time: 0.9850881099700928 seconds
NumPy array time: 0.032288551330566406 seconds


In [2]:
# Memory Usage comparison  
import sys
print("Python list size:", sys.getsizeof(python_list) * len(python_list)) 
print("NumPy array size:", np_array.nbytes) 

Python list size: 800000560000000
NumPy array size: 80000000


### 3. NumPy Array (ndarray) Basics

In [3]:
# Creating Arrays
arr1 = np.array([1, 2, 3])
arr2 = np.zeros((2, 3))
arr3 = np.ones((3, 3))
arr4 = np.arange(0, 10, 2)
arr5 = np.linspace(1, 10, 5)
# We can also explicitly change the dtype for our arrays.
str_arr = np.array([1, 2, 3], dtype="U")

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(str_arr)

[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[ 1.    3.25  5.5   7.75 10.  ]
['1' '2' '3']


In [4]:
# Array Attributes
arr = np.array([1, 2, 3, 4, 5])

print(arr.ndim )    # number of dimensions
print(arr.shape)    # rows, columns
print(arr.size)     # total elements
print(arr.dtype)    # data type
print(arr.itemsize) # bytes per element
print(arr.nbytes)   # total memory used

1
(5,)
5
int64
8
40


### 4. Indexing & Slicing

In [5]:
arr = np.array([10,20,30,40,50])

print(arr[0])     # first element
print(arr[-1])    # last element
print(arr[1:4])   # slicing
print(arr[::-1])  # reverse array

10
50
[20 30 40]
[50 40 30 20 10]


In [6]:
# 2D indexing:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[1,2]) # get element
print(matrix[1, :]) # second row
print(matrix[:, 0]) # first column
print(matrix[1:3, 1:3]) # mid elements of row 2,3 and column 2,3

6
[4 5 6]
[1 4 7]
[[5 6]
 [8 9]]


In [7]:
# Boolean indexing:
print(arr[arr > 20])
print(arr[arr % 3 == 0])

[30 40 50]
[30]


In [8]:
# Fancy indexing:
arr[[0, 3, 4]]

array([10, 40, 50])

### 5. Array Operations (Vectorized)

**Vectorization** 
Vectorization means performing **operations on entire arrays at once** without explicit 
Python loops.  
- NumPy uses **C-level implementations** internally → much faster than Python loops. 
- Makes code **shorter, cleaner, and faster**. 

In [9]:
# Arithmetic
print(arr + 5)
print(arr - 3)
print(arr * 2)
print(arr ** 2)
print(arr1 + arr2)

[15 25 35 45 55]
[ 7 17 27 37 47]
[ 20  40  60  80 100]
[ 100  400  900 1600 2500]
[[1. 2. 3.]
 [1. 2. 3.]]


In [10]:
# Statistical
print(arr.mean())
print(arr.sum())
print(arr.min())
print(arr.max())
print(arr.std())

30.0
150
10
50
14.142135623730951


In [11]:
# Comparison
print(arr1 > arr2)
print(np.equal(arr1, arr2))

[[ True  True  True]
 [ True  True  True]]
[[False False False]
 [False False False]]


### 6. Data Types in NumPy

We have already discussed how every NumPy array has a **single data type** (homogeneous arrays) & it is stored in the `.dtype` attribute.
Now, let’s look into some of the most **common data types** in NumPy:
- Integer literals : `int32`, `int64` 
- Floating literals : `float32`, `float64`
- Boolean : `bool`
- Complex numbers : `complex64`, `complex128`
- String : `S` (byte-str) & `U` (unicode-str)   
- Object : generic python objects – `object`

In [12]:
# Common Data Types  
arr = np.array([1, 2, 3, 4, 5])  
arr2 = np.array([1.0, 2.0, 3.0])  
arr3 = np.array(["hello", "world", "prime", "ai/ml"])  

print(arr.dtype) # int64 
print(arr2.dtype) # float64  
print(arr3.dtype) # U  

# Complex Numbers  |
arr1 = np.array([2 + 3j])  
arr2 = np.array([5 + 8j])  

print(arr1, arr1.dtype)  
print(arr1 + arr2)  
print(arr2 - arr1)  

# Objects  
arr = np.array (["hello", {1, 2, 3}, 3.14])  
print(arr, arr.dtype) 

int64
float64
<U5
[2.+3.j] complex128
[7.+11.j]
[3.+5.j]
['hello' {1, 2, 3} 3.14] object


##### We can also change the data type, either by explicitly typecasting at array creation using `dtype` attribute or by using the `astype` method while creating a new array from an existing one. 

In [13]:
# Changing the data type  
arr = np.array([1, 2, 3, 4, 5])

new_arr = arr.astype("float64")  
print(new_arr, new_arr.dtype)  

new_arr = np.array([1, 2, 3, 4, 5], dtype="float64")  
print(new_arr, new_arr.dtype) 

[1. 2. 3. 4. 5.] float64
[1. 2. 3. 4. 5.] float64


**Why does dtype matter?**
- Memory efficiency 
  - `np.int8` uses 1 byte per element, `np.int64` uses 8 bytes. 
- Performance
  - Smaller types = faster computations. 
- Compatibility 
  - Images often use `np.uint8` 
  - ML libraries expect `float32`

### 7. Important NumPy Functions

In [14]:
# Creating arrays:
print(np.full((3,3), 8))
print(np.eye(4)) # identity matrix
print(np.random.rand(3,3))
print(np.random.randint(1, 10, (3,3)))

[[8 8 8]
 [8 8 8]
 [8 8 8]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.5202901  0.33953134 0.59114395]
 [0.53186537 0.95592881 0.24805683]
 [0.39765812 0.33490811 0.63036252]]
[[3 1 4]
 [2 1 6]
 [9 4 9]]


In [15]:
# Reshaping:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr.reshape(3, 2))
print(arr.ravel()) # flatten
print(arr.flatten())
print(arr.T) # transpose

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [16]:
# Stacking:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

print(np.hstack([a, b]))
print(np.vstack([a, b]))
print(np.concatenate([a,b], axis=0))

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 8. Broadcasting (VERY IMPORTANT)

**Broadcasting**
Broadcasting allows NumPy to **automatically expand arrays of different shapes** so that
arithmetic operations can be performed. It’s basically scaling arrays without using extra memory. 
- No need to manually reshape arrays. 
- Useful for **combining arrays of different dimensions**.
  
**Broadcasting Rules**
Broadcasting can only take place when the arrays are of compatible shape. So NumPy compares shapes of arrays
from **right to left**. For the array to be compatible, all dimensions must either be:
- Equal, or 
- 1, or 
- Missing (smaller array can be “stretched”).

NumPy applies operations between arrays of different shapes.

##### Example:

In [17]:
arr = np.array([1,2,3])
matrix = np.ones((3,3))

# NumPy expands the smaller array automatically.
matrix + arr

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

### 9. Linear Algebra (Essential for ML)

In [18]:
print(np.dot(a, b))
print(a @ b) # matrix multiplication
print(np.linalg.inv(a)) # inverse
print(np.linalg.det(a)) # determinant
print(np.linalg.eig(a)) # eigen values/vectors

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


### 10. Random Module

In [19]:
# Useful for ML model initialization and data splitting.
print(np.random.seed(0)) # to fix random values
print(np.random.randn(3,3))
print(np.random.randint(1, 10, size=5))

None
[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]]
[7 8 8 9 2]


In [20]:
np.random.shuffle(arr)
arr

array([1, 3, 2])

### 11. In-place & Copy

In [21]:
b = a            # no copy
c = a.copy()     # deep copy
# Avoids accidental modification.

### 12. Memory & Speed Optimization

Use:

- `dtype=np.float32` instead of float64
- `np.vectorize()` to apply on whole array
- Avoid Python loops
- Use broadcasting instead of repmat
- Use `np.fromiter()` for fast creation

### 13. Useful Mathematical Functions
NumPy is massive & provides a **wide range of built-in mathematical functions** that are highly optimized and
can operate **element-wise on arrays**. Let’s have a look at some of them: 

**Aggregation Functions**
These are functions that take an array and reduce it to a single value (or smaller array) 
by combining elements.
- `sum()` - returns sum of all elements
- `prod()` - returns product of all elements 
- `min()` - returns minimum value 
- `max()` - returns maximum value
- `argmin()` - returns index of min value
- `argmax()` - returns index of max value
- `mean()` - returns mean (average)
- `median()` - returns median
- `std()` - returns standard deviation 
- `var()` - returns variance 

In [22]:
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))  # 15 
print(np.prod(arr)) # 120  
print(np.min(arr)) # 1  
print(np.argmin(arr)) # 0 
print(np.max(arr)) # 5  
print(np.argmax(arr)) # 4  
print(np.mean(arr)) # 3.0  
print(np.median(arr)) # 3.0  
print(np.std(arr)) # 1.41  
print(np.var(arr)) # 2.0 

15
120
1
0
5
4
3.0
3.0
1.4142135623730951
2.0


**Power Functions**
- `square()` - returns square of all elements
- `sqrt()` - returns square root of all elements
- `pow(a, b)` - returns ab

In [23]:
arr = np.array([1, 2, 3, 4, 5]) 

print(np.square(arr))  # [1, 4, 9, 16, 25] 
print(np.sqrt(arr))  # [1, 1.41, 1.73, 2, 2.23]  
print(np.pow(arr, 3))  # [1, 8, 27, 64, 125]

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


**Log & Exponential Functions**
- `log()` - returns natural log
- `log10()` - returns log base 10 
- `log2()` - returns log base 2
- `exp(x)` - returns ex 

In [24]:
print(np.log(arr))  
print(np.log10(arr))  
print(np.log2(arr))  
print(np.exp(arr)) 

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


**Rounding Functions**
- `round()` - rounds off to nearest value 
- `ceil()` - rounds up 
- `floor()` - rounds down
- `trunc(x)` - truncates(removes) the fractional part  

In [25]:
print(np.round(2.678)) # 3.0  
print(np.floor(2.678)) # 2.0 
print(np.ceil(2.678))  # 3.0  
print(np.trunc(2.678)) # 2.0 

3.0
2.0
3.0
2.0


**Miscellaneous Functions**
- `abs()` - returns absolute value
- `sort()` - returns sorted(arranges in increasing order) values 
- `unique()` - returns unique values

In [26]:
arr = np.array([1, 2, -5, 3, 8, -4, 2, 5]) 

print(np.abs(arr))  # [1 2 5 3 8 4 2 5]  
print(np.sort(arr)) # [-5 -4 1 2 2 3 5 8] 
print(np.unique(arr)) # [-5 -4 1 2 3 5 8] 

[1 2 5 3 8 4 2 5]
[-5 -4  1  2  2  3  5  8]
[-5 -4  1  2  3  5  8]


### 14. ADVANCED NUMPY

#### 1. Strides

In [27]:
# Strides tell NumPy how many bytes to skip in memory to get to the next element.
arr = np.array([10, 20, 30, 40])
slice_arr = arr[1:4:2]   # take every 2nd element from index 1 → [20, 40]

print("Array:", arr)
print("Slice:", slice_arr)
print("Original Strides:", arr.strides)
print("Slice Strides:", slice_arr.strides)

Array: [10 20 30 40]
Slice: [20 40]
Original Strides: (8,)
Slice Strides: (16,)


#### 2. Views vs Copies

Slicing a list returns a copy but slicing a NumPy array returns a view - for efficiency. 
View is like a shallow copy that shares the same data as the original array, so no 
duplication happens here. 

- **Views** are fast and memory-efficient (no data duplication). 
- **Copies** are safe but slower and use more memory.

In [28]:
# Slicing gives a VIEW (no new memory)
arr = np.array([1,2,3,4])
view = arr[1:3] # view → points to same memory
view[0] = 99

print(arr) # arr changes!

[ 1 99  3  4]


In [29]:
# copy() creates a NEW array
arr = np.array([1,2,3])
copy_arr = arr.copy()
copy_arr[0] = 99

print(arr)       # unchanged
print(copy_arr)

[1 2 3]
[99  2  3]


#### 3. np.where()

In [30]:
arr = np.array([5, 12, 3, 18])

result = np.where(arr > 10, "big", "small")
print(result)

['small' 'big' 'small' 'big']


#### 4. Masked Arrays

In [31]:
# Mask elements that meet a condition.
arr = np.array([5, 12, -1, 18])
masked = np.ma.masked_where(arr < 0, arr)
# The negative value becomes masked.
print(masked)

[5 12 -- 18]


#### 5. Structured Arrays

In [32]:
# Store mixed data types (like a table with columns).
data = np.array([
    (1, 'Alice', 85.5),
    (2, 'Bob', 90.0)
],
dtype=[('id', 'i4'), ('name', 'U10'), ('score', 'f4')])

print(data['name'])
print(data['score'])

['Alice' 'Bob']
[85.5 90. ]


#### 6. Vectorization of a Custom Function

In [33]:
# Convert a Python function into a vectorized NumPy function.
f = np.vectorize(lambda x: x*2)
arr = np.array([1,2,3,4])
print(f(arr))

[2 4 6 8]


#### 7. Performance Tools

##### np.einsum() (Einstein Summation)

In [34]:
# Fast, flexible matrix operations.
a = np.array([1,2,3])
b = np.array([4,5,6])

dot = np.einsum('i,i->', a, b)
print(dot)

32


- `'i'` = index
- `'i,i'` = multiply matching elements
- `'->'` = sum them (because no output indices)
- Result = dot product

##### np.matmul() (matrix multiplication)

In [35]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])

print(np.matmul(A, B))

[[19 22]
 [43 50]]


##### numexpr (fast expression evaluation)

In [36]:
# Much faster than regular NumPy operations.
import numexpr as ne
a = np.arange(1000000)
b = np.arange(1000000)

c = ne.evaluate("a * 2 + b * 3")
c

array([      0,       5,      10, ..., 4999985, 4999990, 4999995])

##### numba (JIT Compiler — speeds up Python loops)

In [37]:
# Runs 10–100x faster.
from numba import njit

@njit
def fast_sum(arr):
    total = 0
    for x in arr:
        total += x
    return total

print(fast_sum(np.arange(1000000)))

499999500000


### 15. Most Important NumPy Interview Questions

- Difference between list & ndarray
- What is broadcasting?
- Vectorization in NumPy
- `reshape()` vs `resize()`
- View vs Copy
- What are strides?
- How NumPy is faster than Python?
- `ravel()` vs `flatten()`
- Difference between `np.array()` and `np.asarray()`
- What is memory layout (C vs F order)?