## NUMPY COMPLETE GUIDE

### 1. What is NumPy?

NumPy (Numerical Python) is the fastest numerical computing library in Python.
It provides:

- ndarray → fast multi-dimensional arrays
- vectorized operations → no loops, extremely fast
- mathematical functions
- linear algebra
- random number generation

NumPy is written in C, which is why it's much faster than Python lists.

### 2. Why NumPy Instead of Lists?

- **Speed**
  - Lists → Slow  
  - NumPy → **50–100x faster**

- **Memory**
  - Lists → High  
  - NumPy → **Low memory usage**

- **Operations**
  - Lists → Uses loops  
  - NumPy → **Vectorized operations (no loops)**

- **Data Types**
  - Lists → Mixed data types allowed  
  - NumPy → **Homogeneous data types**

- **Machine Learning Support**
  - Lists → Poor support  
  - NumPy → **Essential for ML & scientific computing**


### 3. NumPy Array (ndarray) Basics

In [2]:
# Creating Arrays
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.zeros((2, 3))
arr3 = np.ones((3, 3))
arr4 = np.arange(0, 10, 2)
arr5 = np.linspace(1, 10, 5)

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)

[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[ 1.    3.25  5.5   7.75 10.  ]


In [5]:
# Array Attributes
arr = np.array([1, 2, 3, 4, 5])

print(arr.ndim )    # number of dimensions
print(arr.shape)    # rows, columns
print(arr.size)     # total elements
print(arr.dtype)    # data type
print(arr.itemsize) # bytes per element
print(arr.nbytes)   # total memory used

1
(5,)
5
int64
8
40


### 4. Indexing & Slicing

In [6]:
arr = np.array([10,20,30,40,50])

print(arr[0])     # first element
print(arr[-1])    # last element
print(arr[1:4])   # slicing
print(arr[::-1])  # reverse array

10
50
[20 30 40]
[50 40 30 20 10]


In [8]:
# 2D indexing:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[1,2]) # get element
print(matrix[1, :]) # second row
print(matrix[:, 0]) # first column
print(matrix[1:3, 1:3]) # mid elements of row 2,3 and column 2,3

6
[4 5 6]
[1 4 7]
[[5 6]
 [8 9]]


In [11]:
# Boolean indexing:
print(arr[arr > 20])
print(arr[arr % 3 == 0])

[30 40 50]
[30]


In [12]:
# Fancy indexing:
arr[[0, 3, 4]]

array([10, 40, 50])

### 5. Array Operations (Vectorized)

In [13]:
# Arithmetic
print(arr + 5)
print(arr - 3)
print(arr * 2)
print(arr ** 2)
print(arr1 + arr2)

[15 25 35 45 55]
[ 7 17 27 37 47]
[ 20  40  60  80 100]
[ 100  400  900 1600 2500]
[[1. 2. 3.]
 [1. 2. 3.]]


In [14]:
# Statistical
print(arr.mean())
print(arr.sum())
print(arr.min())
print(arr.max())
print(arr.std())

30.0
150
10
50
14.142135623730951


In [15]:
# Comparison
print(arr1 > arr2)
print(np.equal(arr1, arr2))

[[ True  True  True]
 [ True  True  True]]
[[False False False]
 [False False False]]


### 6. Important NumPy Functions

In [16]:
# Creating arrays:
print(np.full((3,3), 8))
print(np.eye(4)) # identity matrix
print(np.random.rand(3,3))
print(np.random.randint(1, 10, (3,3)))

[[8 8 8]
 [8 8 8]
 [8 8 8]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.2556304  0.42567038 0.66722789]
 [0.24420047 0.43165143 0.33863424]
 [0.61179391 0.11500096 0.76684668]]
[[7 2 8]
 [7 6 8]
 [1 2 4]]


In [22]:
# Reshaping:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr.reshape(3, 2))
print(arr.ravel()) # flatten
print(arr.flatten())
print(arr.T) # transpose

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [25]:
# Stacking:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

print(np.hstack([a, b]))
print(np.vstack([a, b]))
print(np.concatenate([a,b], axis=0))

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 7. Broadcasting (VERY IMPORTANT)

NumPy applies operations between arrays of different shapes.

##### Example:

In [26]:
arr = np.array([1,2,3])
matrix = np.ones((3,3))

# NumPy expands the smaller array automatically.
matrix + arr

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

### 8. Linear Algebra (Essential for ML)

In [27]:
print(np.dot(a, b))
print(a @ b) # matrix multiplication
print(np.linalg.inv(a)) # inverse
print(np.linalg.det(a)) # determinant
print(np.linalg.eig(a)) # eigen values/vectors

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


### 9. Random Module

In [41]:
# Useful for ML model initialization and data splitting.
print(np.random.seed(0)) # to fix random values
print(np.random.randn(3,3))
print(np.random.randint(1, 10, size=5))

None
[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]]
[7 8 8 9 2]


In [50]:
np.random.shuffle(arr)
arr

array([3, 2, 1])

### 10. In-place & Copy

In [51]:
b = a            # no copy
c = a.copy()     # deep copy
# Avoids accidental modification.

### 11. Memory & Speed Optimization

Use:

- `dtype=np.float32` instead of float64
- `np.vectorize()` to apply on whole array
- Avoid Python loops
- Use broadcasting instead of repmat
- Use `np.fromiter()` for fast creation

### 12. ADVANCED NUMPY

#### 1. Strides

In [54]:
# Strides tell NumPy how many bytes to skip in memory to get to the next element.
arr = np.array([10, 20, 30, 40])
slice_arr = arr[1:4:2]   # take every 2nd element from index 1 → [20, 40]

print("Array:", arr)
print("Slice:", slice_arr)
print("Original Strides:", arr.strides)
print("Slice Strides:", slice_arr.strides)

Array: [10 20 30 40]
Slice: [20 40]
Original Strides: (8,)
Slice Strides: (16,)


#### 2. Views vs Copies

In [55]:
# Slicing gives a VIEW (no new memory)
arr = np.array([1,2,3,4])
view = arr[1:3] # view → points to same memory
view[0] = 99

print(arr) # arr changes!

[ 1 99  3  4]


In [56]:
# copy() creates a NEW array
arr = np.array([1,2,3])
copy_arr = arr.copy()
copy_arr[0] = 99

print(arr)       # unchanged
print(copy_arr)

[1 2 3]
[99  2  3]


#### 3. np.where()

In [57]:
arr = np.array([5, 12, 3, 18])

result = np.where(arr > 10, "big", "small")
print(result)

['small' 'big' 'small' 'big']


#### 4. Masked Arrays

In [60]:
# Mask elements that meet a condition.
arr = np.array([5, 12, -1, 18])
masked = np.ma.masked_where(arr < 0, arr)
# The negative value becomes masked.
print(masked)

[5 12 -- 18]


#### 5. Structured Arrays

In [61]:
# Store mixed data types (like a table with columns).
data = np.array([
    (1, 'Alice', 85.5),
    (2, 'Bob', 90.0)
],
dtype=[('id', 'i4'), ('name', 'U10'), ('score', 'f4')])

print(data['name'])
print(data['score'])

['Alice' 'Bob']
[85.5 90. ]


#### 6. Vectorization of a Custom Function

In [62]:
# Convert a Python function into a vectorized NumPy function.
f = np.vectorize(lambda x: x*2)
arr = np.array([1,2,3,4])
print(f(arr))

[2 4 6 8]


#### 7. Performance Tools

##### np.einsum() (Einstein Summation)

In [64]:
# Fast, flexible matrix operations.
a = np.array([1,2,3])
b = np.array([4,5,6])

dot = np.einsum('i,i->', a, b)
print(dot)

32


- `'i'` = index
- `'i,i'` = multiply matching elements
- `'->'` = sum them (because no output indices)
- Result = dot product

##### np.matmul() (matrix multiplication)

In [65]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])

print(np.matmul(A, B))

[[19 22]
 [43 50]]


##### numexpr (fast expression evaluation)

In [67]:
# Much faster than regular NumPy operations.
import numexpr as ne
a = np.arange(1000000)
b = np.arange(1000000)

c = ne.evaluate("a * 2 + b * 3")
c

array([      0,       5,      10, ..., 4999985, 4999990, 4999995])

##### numba (JIT Compiler — speeds up Python loops)

In [68]:
# Runs 10–100x faster.
from numba import njit

@njit
def fast_sum(arr):
    total = 0
    for x in arr:
        total += x
    return total

print(fast_sum(np.arange(1000000)))

499999500000


### 13. Most Important NumPy Interview Questions

- Difference between list & ndarray
- What is broadcasting?
- Vectorization in NumPy
- `reshape()` vs `resize()`
- View vs Copy
- What are strides?
- How NumPy is faster than Python?
- `ravel()` vs `flatten()`
- Difference between `np.array()` and `np.asarray()`
- What is memory layout (C vs F order)?