## 100 numpy exercises

#### 1. Import the numpy package under the name `np`

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [2]:
np.__version__

'2.1.3'

In [3]:
np.__config__

<module 'numpy.__config__' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\numpy\\__config__.py'>

#### 3. Create a null vector of size 10

In [8]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array

In [11]:
print("%d bytes" % (z.size * z.itemsize))

80 bytes


In [12]:
# Simpler alternative
print("%d bytes" % z.nbytes)

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line?

In [17]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [18]:
null_vector = np.zeros(10)
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49

In [19]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last)

In [22]:
vector = np.arange(1, 11)
vector[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [24]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [51]:
arr1 = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(arr1)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix

In [52]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [53]:
np.random.random((3,3,3))

array([[[0.2399667 , 0.59398805, 0.50621053],
        [0.46172374, 0.44428414, 0.77268877],
        [0.71729706, 0.92772176, 0.49232191]],

       [[0.19671211, 0.24806888, 0.48117042],
        [0.20271184, 0.14370173, 0.06817749],
        [0.93824062, 0.37106378, 0.98547811]],

       [[0.16402131, 0.20655144, 0.32401329],
        [0.13320492, 0.51191772, 0.61606304],
        [0.93795735, 0.44603458, 0.63756118]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [54]:
arr2 = np.random.random((10, 10))
arr2

array([[0.32803738, 0.38723227, 0.64741245, 0.64064407, 0.33019051,
        0.6700408 , 0.26596777, 0.95343433, 0.82491954, 0.81205284],
       [0.80146168, 0.42690747, 0.34091586, 0.07137918, 0.81814028,
        0.30588595, 0.27543049, 0.02830789, 0.6601846 , 0.45792992],
       [0.71371721, 0.20183021, 0.35479116, 0.02180288, 0.28779802,
        0.84309673, 0.50158328, 0.40231402, 0.76393051, 0.85754654],
       [0.85371303, 0.40682941, 0.63932884, 0.96027566, 0.79701298,
        0.8542299 , 0.06450557, 0.04728893, 0.2315643 , 0.85288556],
       [0.75400561, 0.46666992, 0.70212784, 0.12914678, 0.80962645,
        0.38410968, 0.33042319, 0.56403756, 0.21407162, 0.90815374],
       [0.3844287 , 0.76510906, 0.68856437, 0.22145219, 0.68498053,
        0.91199538, 0.42006431, 0.26519758, 0.30088109, 0.09574696],
       [0.07384213, 0.95509739, 0.13220207, 0.9470306 , 0.19339631,
        0.25901362, 0.51319756, 0.6811725 , 0.53384541, 0.15069733],
       [0.17846168, 0.92357915, 0.3784133

In [55]:
print(arr2.max())

0.9983268401812371


In [56]:
print(arr2.min())

0.021802878690358463


#### 14. Create a random vector of size 30 and find the mean value

In [57]:
arr3 = np.random.random(30)
arr3

array([0.01522065, 0.27962132, 0.75814555, 0.20615488, 0.3819781 ,
       0.59232989, 0.90002375, 0.3161222 , 0.7577031 , 0.19182876,
       0.80122625, 0.22273107, 0.96222334, 0.10235005, 0.22115447,
       0.74607145, 0.00322131, 0.77737298, 0.95358826, 0.5745766 ,
       0.6790159 , 0.38963029, 0.08178568, 0.7712754 , 0.56255255,
       0.20217415, 0.38681717, 0.90147887, 0.57698595, 0.2830172 ])

In [58]:
print(arr3.mean())

0.48661257126573765


#### 15. Create a 2d array with 1 on the border and 0 inside

In [59]:
arr4 = np.ones((10, 10))
arr4[1:-1,1:-1] = 0
arr4

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [61]:
arr5 = np.ones((5, 5))
arr5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [90]:
arr5 = np.pad(arr5, pad_width=1, mode='constant', constant_values=0)
arr5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### `pad_width=1`

This means:

- Add 1 layer of padding on every side
- Applies to all dimensions
- For a 2D array:
  - 1 row on top
  - 1 row on bottom
  - 1 column on left
  - 1 column on right

So the padded array becomes larger by +2 in each dimension.

Example:
If `arr5` is shape `(m, n)`, new shape = `(m+2, n+2)`.

#### `mode='constant'`
This means the padding values will be constant (not reflected, repeated, etc.).

#### `constant_values=0`

This sets the padding value to 0.
So the border is filled with zeros.

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [91]:
# Any arithmetic operation involving NaN produces NaN
print(0 * np.nan)

nan


In [92]:
# NaN is not equal to anything, including itself.
print(np.nan == np.nan)

False


In [93]:
# Any comparison involving NaN returns False, except !=, which returns True.
# np.nan is unordered: it is not greater, less, or equal to anything.
print(np.inf > np.nan)

False


In [94]:
# Any arithmetic with NaN → NaN.
print(np.nan - np.nan)

nan


In [95]:
print(np.nan in set([np.nan]))

True


Output: `True`, surprisingly!

Why:
This seems contradictory because `np.nan` != `np.nan`, but:

#### Sets use hashing for membership
- `np.nan` has a stable hash value.
- The hash is used first to find the bucket in the set.
- Equality is checked only afterward—but since it's the same object, it is treated as found.

So `x in set([x])` is always true, even if `x != x`.

> Using NaN as a set key works, but using multiple NaNs can behave oddly.

In [96]:
print(0.3 == 3 * 0.1)

False


Output: `False`

Why:
This is due to binary floating-point precision.

- `0.1` cannot be represented exactly in binary.
- `3 * 0.1` becomes `0.30000000000000004`

This is not exactly equal to 0.3

In [97]:
print(3 * 0.1)

0.30000000000000004


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [98]:
arr6 = np.diag(1+np.arange(4),k=-1)
arr6

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [99]:
# explanation
np.arange(4)

array([0, 1, 2, 3])

In [100]:
1 + np.arange(4)

array([1, 2, 3, 4])

`np.diag(values, k=-1)`

`np.diag(v, k)` places the 1D array `v` on a diagonal:

- `k = 0` → main diagonal
- `k = 1` → 1 above main
- `k = -1` → 1 below main (sub-diagonal)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [101]:
arr7 = np.zeros((8,8),dtype=int)
# odd columns
arr7[1::2,::2] = 1
# even columns
arr7[::2,1::2] = 1
arr7

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [103]:
# Index 99 is a location in the flattened (1D) version of this array.
# np.unravel_index(99, (6,7,8)) finds the corresponding (i, j, k) position in the 3-D array using row-major (C-style) order.
np.unravel_index(99,(6,7,8))

(np.int64(1), np.int64(5), np.int64(3))